name: Run Script Daily

on:
    schedule:
        - cron: "0 2 * * *" # Runs at 21:00 CST daily (2AM UTC)
    workflow_dispatch:

jobs:
    run-script:
        runs-on: ubuntu-latest

        env:
            TZ: America/Chicago # Set your desired time zone here

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.SUBMODULE_PAT }}
                  persist-credentials: false
                  submodules: recursive

            - name: Set up Node.js
              uses: actions/setup-node@v3 # Sets up Node.js environment
              with:
                  node-version: "16" # Specify the Node.js version you need

            - name: Install dependencies
              run: |
                  export PUPPETEER_DOWNLOAD_TIMEOUT=100000
                  npm install # Install dependencies defined in package.json

            - name: Run script
              run: node 'DWP Reports/runDailyDWPReports.js'
              env:
                  PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome-stable"

            - name: Configure git
              run: |
                  git config --global user.name "adnguyen527"
                  git config --global user.email "adnguyen527@gmail.com"

            - name: Ensure clean working directory in submodule
              run: |
                  cd report-data
                  git remote set-url origin https://x-access-token:${{ secrets.SUBMODULE_PAT }}@github.com/adnguyen527/report-data.git
                  git fetch origin
                  git checkout -f main
                  # Apply orphan commit to main branch if it exists
                  orphan_commit_sha=$(git reflog show --format=%H | grep -v -E '^[0-9a-f]{7}' | head -n 1)
                  if [ -n "$orphan_commit_sha" ]; then
                    git cherry-pick $orphan_commit_sha || echo "Conflict during cherry-pick. Manual intervention might be required."
                  fi
                  git reset --hard
                  git clean -fd

            - name: Commit changes to submodule
              run: |
                  cd report-data
                  git add .
                  # Commit with the current date in the message
                  git commit -m "Add downloaded files - $(date +'%Y-%m-%d')" || echo "No changes to commit"
                  git push

            - name: Update main repository submodule reference
              run: |
                  cd $GITHUB_WORKSPACE
                  git add report-data
                  git commit -m "Update submodule reference - $(date +'%Y-%m-%d')" || echo "No changes to commit"
                  git remote set-url origin https://x-access-token:${{ secrets.SUBMODULE_PAT }}@github.com/adnguyen527/StudentDirectory.git
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.SUBMODULE_PAT }}
