name: Run Script Daily

on:
    schedule:
        - cron: "0 2 * * *" # Runs at 21:00 CST daily (2AM UTC)
    workflow_dispatch:

jobs:
    run-script:
        runs-on: ubuntu-latest

        env:
            TZ: America/Chicago # Set your desired time zone here

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  persist-credentials: false
                  submodules: recursive

            - name: Set up Node.js
              uses: actions/setup-node@v3 # Sets up Node.js environment
              with:
                  node-version: "16" # Specify the Node.js version you need

            - name: Install dependencies
              run: |
                  export PUPPETEER_DOWNLOAD_TIMEOUT=100000
                  npm install # Install dependencies defined in package.json

            - name: Run script
              run: node 'DWP Reports/runDailyDWPReports.js'
              env:
                  PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome-stable"

            - name: Configure git
              run: |
                  git config --global user.name "adnguyen527"
                  git config --global user.email "adnguyen527@gmail.com"

            - name: Commit changes to submodule
              run: |
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/adnguyen527/report-data.git
                  git submodule update --remote --merge
                  cd report-data
                  git add .
                  # Commit with the current date in the message
                  git commit -m "Add downloaded files - $(date +'%Y-%m-%d')" || echo "No changes to commit"
                  git push origin main

            - name: Update main repository submodule reference
              run: |
                  cd $GITHUB_WORKSPACE
                  git add report-data
                  git commit -m "Update submodule reference - $(date +'%Y-%m-%d')" || echo "No changes to commit"
                  git stash
                  git pull origin ${{github.ref_name}} --rebase || exit 1 # Ensure have the latest changes
                  git stash pop || echo "No stashed changes to apply"
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/adnguyen527/StudentDirectory.git
                  git push origin ${{github.ref_name}}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
